---
deployment:
  tasks:
    - export DEPLOYPATH=/home/valosyst/public_html/tsgalaxyfc.valosystems.co.za
    - /bin/mkdir -p $DEPLOYPATH
    - /bin/find $DEPLOYPATH -mindepth 1 -maxdepth 1 -exec /bin/rm -rf {} +
    - /bin/cp -R dist/. $DEPLOYPATH
    - /bin/cp .htaccess $DEPLOYPATH/.htaccess
    - /bin/find $DEPLOYPATH -type d -exec /bin/chmod 755 {} +
    - /bin/find $DEPLOYPATH -type f -exec /bin/chmod 644 {} +
